### ISSUE TITLE
Reset Password (Change password)

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#10]
**Endpoint: /api/auth/password/change**
Method: POST
Description: Allows users to reset their password after verifying their identity with a code sent to their email.
Authorization Required: No

**Parameters:**
    Email Address: User's email address.
    Verification Code: The code sent to the user's email for verification.
    New Password: The new password the user wants to set.

Validations:
**Email Address:**
    Must be in a valid email format.
    Ensure the email is associated with a verified password reset request.
**Verification Code:**
    Must be valid and match the code sent to the user's email.
    Ensure the code has not expired.
**New Password:**
    Must meet complexity requirements (e.g., minimum 8 characters, includes numbers).
    Ensure the new password is different from the previous password to enhance security.

Security Measures:
    Code Verification and Expiry: Verify the code is correct and check that it has not expired before allowing the password change.
    Password Encryption: Encrypt the new password using a strong hashing algorithm before storing it in the database to ensure it is securely saved.

**Feedback:**
    Successful Reset: Provide a confirmation message such as "Your password has been successfully reset. You can now log in with your new password."
    Failed Attempts: In case of incorrect code or other issues, provide feedback like "Invalid or expired verification code. Please restart the password recovery process."

Note: Add test cases for all scenarios

**Comment by muchinon** [comment]
@alexboateng I want to pick up this issue

**Comment by muchinon** [comment]
https://github.com/mestafrica/mobile-wallet-fraud-database/pull/38
