### ISSUE TITLE
Admin - Reset Password (Send Email)

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#100]
**Endpoint: /api/admin/password/recover**
Method: POST
Description: Initiates the password recovery process by sending a reset code to the admin's email.
Authorization Required: No
Parameters:
Email: Admin's email address.

**Validations:**
Email Address:
Must be in a valid email format.
Verify that the email exists in the admin database.

**Feedback:**
Success: "If your email address is registered, you will receive a reset code shortly."
Failure: "Failed to initiate password recovery. Please check the email provided."

**Comment by Wise-mystic** [comment]
I am Wisdom Kwawuvi and I'm ready to handle this task

**Comment by Wise-mystic** [comment]
#110  ready for in this assignment
