### ISSUE TITLE
Admin - Reset Password (Verify Code)

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#101]
**Endpoint: /api/admin/password/verify-code**
Method: POST
Description: Verifies the reset code sent to the admin's email during the password recovery process.
Authorization Required: No
Parameters:
Email Address: Admin's email address.
Code: Verification code.

**Validations:**
Code:
Must match the code sent.
Ensure the code has not expired.

**Feedback:**
Success: "Code verified successfully."
Failure: "Invalid or expired code."

**Comment by Andrew-Sackey** [comment]
@alexboateng my name is Andrew and i want to be assigned this issue.
