### ISSUE TITLE
Admin - Reset Password (Change password)

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#102]
**Endpoint: /api/admin/password/change**
Method: POST
Description: Allows admins to reset their password after a successful code verification.
Authorization Required: No

**Parameters:**
Email Address: Admin's email address.
New Password: New password to be set.

**Validations:**
New Password:
Must meet complexity requirements.
Must be different from the previous password.

**Feedback:**
Success: "Password changed successfully."
Failure: "Failed to change password. Please ensure your new password meets all requirements."

**Comment by Barmoo** [comment]
#102 Alex please I want to be assigned password reset
