### ISSUE TITLE
Admin - Create an Admin

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#112]
**Endpoint: /api/admin/users/add**
Method: POST
Description: Adds a new admin with specified permissions.
Authorization Required: Yes

**Parameters:**
First Name: Admin's first name.
Last Name: Admin's last name.
Email: Admin's email address.
Phone Number: Admin's phone number.
Passwor: New password for admin.
Permissions: Specific administrative permissions such as approving fraud reports, setting API key limits, etc.

Permissions
Can approve fraud report
Can delete or remove fraud report
Can set API key usage limit
Can set domain restrictions
Can set domain restrictions
Can deactivate user’s account
Can set system configuration
Can add or remove admins

**Validations:**
Email Address:
Must be unique and in a valid email format.

Feedback:
Success: "New admin added successfully."
Failure: "Failed to add new admin. Please check the provided details."

**Comment by Andrew-Sackey** [comment]
Please i want to be assigned to this issue
