### ISSUE TITLE
Admins - Deactivate & Delete Admins

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#114]
**Endpoint: /api/admin/users/deactivate/{adminId}**
Method: POST
Description: Deactivates an admin's account, preventing them from logging in or performing any administrative actions.
Authorization Required: Yes

**Parameters:**
Admin ID: The unique identifier for the admin.

**Feedback:**
Success: "Admin account deactivated successfully."
Failure: "Failed to deactivate admin account. Please try again."

**Endpoint: /api/admin/users/delete/{adminId}**
Method: DELETE
Description: Permanently deletes an admin's account from the system.
Authorization Required: Yes

**Parameters:**
Admin ID: The unique identifier for the admin.

**Feedback:**
Success: "Admin account deleted successfully."
Failure: "Failed to delete admin account. Please ensure the admin ID is correct and try again."

**Comment by Barmoo** [comment]
#114 kindly assign this task to me
