### ISSUE TITLE
Admin - List admins

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#115]
**Endpoint: /api/admin/users/list**
Method: GET
Description: Lists all active admin users, providing details such as names, emails, phone numbers, permissions and current status.
Authorization Required: Yes

**Feedback:**
Success: Returns a detailed list of all admins.
Failure: "You do not have permission to view this information." or any other error

**Comment by Wise-mystic** [comment]
I am willing to take this task
