### ISSUE TITLE
List Fraudulent Reports

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#12]
**Endpoint: /api/fraud/reports**
    Method: GET
    Description: Enables users to view a list of all numbers reported.
    Authorization Required: Yes

**Filters**
  Should be able to filter by phone number, status, date range
  Should be able to filter user added reports only

**Security Measures:**
    Authorization Check: Ensure the user is authenticated to view only their own reports.

**Feedback:**
    Success: Returns a list of fraud reports.
    Failure: "You do not have permission to view these reports" or related errors

Note: Add test cases for all scenarios
For private reports, only authenticated owners of report should be able to retrieve the data

**Comment by Sarah0360** [comment]
@alexboateng I will like to pick up this issue.

**Comment by muchinon** [comment]
completed
