### ISSUE TITLE
Add Automated Network Provider Detection

### ISSUE THREAD

**Issue by muchinon** [mestafrica/FraudWatch#125]
**Endpoint**: /api/utils/network-provider 

**Method**: GET 

**Description**: Automatically identifies the network provider from submitted phone numbers and validates number format 

**Authorization Required**: No

**Parameters**: Phone Number

**Feedback**:
Success: Returns network provider details
Failure: "Invalid phone number format" or "Unknown network provider"

**Comment by Andrew-Sackey** [comment]
Please assign me to this issue
