### ISSUE TITLE
Implement Rate Limiting by Phone Number

### ISSUE THREAD

**Issue by muchinon** [mestafrica/FraudWatch#126]
**Endpoint**: /api/reports/check-limit 

Method: GET 

**Description**: Prevents spam by limiting the number of times a specific phone number can be reported within a time period. 

Authorization Required: No

**Feedback**: 
Success: Returns current report count and limit status 
Failure: "Rate limit exceeded" or "Invalid phone number"

**Comment by Wise-mystic** [comment]
please assign me this issue
