### ISSUE TITLE
Get Fraud Report

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#13]
**Endpoint: /api/fraud/reports/{reportId}**
    Method: GET
    Description: Provides detailed information about a specific fraud report.
    Authorization Required: Yes

**Parameters:**
    Report ID: Unique identifier for the fraud report.
    Security Measures:
    Authorization Check: User must be authenticated and authorized to view the details of the report.

**Feedback:**
    Success: Returns detailed information of the report.
    Failure: "Report not found or you do not have permission to view this report."

Note: Add test cases for all scenarios
For private reports, only authenticated owners of report should be able to retrieve the data

**Comment by muchinon** [comment]
@alexboateng I want to pick up this issue

**Comment by muchinon** [comment]
https://github.com/mestafrica/mobile-wallet-fraud-database/pull/46
