### ISSUE TITLE
Email Verification System

### ISSUE THREAD

**Issue by muchinon** [mestafrica/FraudWatch#136]
**Endpoint**: /api/auth/verify-email

**Method**: POST

**Description**: Sends a verification email to newly registered users and verifies their email upon clicking the link.

Authorization Required: No

**Feedback**:
Success: Returns success message
Failure: "Verification failed" or "Invalid token"

**Comment by Barmoo** [comment]
kindly assign this role to me

**Comment by Barmoo** [comment]
#136 email verification system
kindly assign that to me
