### ISSUE TITLE
User Account Deactivation

### ISSUE THREAD

**Issue by muchinon** [mestafrica/FraudWatch#137]
**Endpoint**: /api/users/deactivate

**Method**: POST

**Description**: Allows users to deactivate their accounts, ensuring their data is handled appropriately.

Authorization Required: Yes

**Feedback**:
Success: Returns account deactivation confirmation
Failure: "Unauthorized" or "Account not found"

**Comment by Andrew-Sackey** [comment]
Please assign me to this issue
