### ISSUE TITLE
Update Report

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#14]
**Endpoint: /api/fraud/reports/update/{reportId}**
    Method: PUT
    Description: Allows users to update their report.
    Authorization Required: Yes

**Parameters:**
    Same as /api/fraud/report, except all fields are optional for updates.
   
**Validations and Security Measures:**
    Similar to /api/fraud/report for each provided field.

**Feedback:**
  Success: "Your fraud report has been successfully updated."
  Failure: Appropriate error message based on the issue.

Note: Add test cases for all scenarios
Only owners of a report can update a report

**Comment by VidaOwusu** [comment]
@alexboateng I want to take up this issue
