### ISSUE TITLE
Admin - Home Dashboard

### ISSUE THREAD

**Issue by muchinon** [mestafrica/FraudWatch#140]
Add UI for Admin Home Dashboard

No data

<img width="850" alt="admin-nodata" src="https://github.com/user-attachments/assets/ff38f076-bb4a-4dcc-8e1b-fbf2c4a07c87">

Data

<img width="845" alt="admin-data" src="https://github.com/user-attachments/assets/6f998fd4-8fe0-4574-8c80-63eff56f2008">

**Comment by Jhacy456** [comment]
@muchinon I will like to take on this issue

**Comment by Jhacy456** [comment]
#149 @muchinon I completed my task and raised a pull request
