### ISSUE TITLE
Admin - API Key Modal

### ISSUE THREAD

**Issue by muchinon** [mestafrica/FraudWatch#141]
After clicking on an API key here: 

<img width="845" alt="admin-data" src="https://github.com/user-attachments/assets/132e89e9-17e9-4ed9-bcbd-749d37aecaaa">

Create this Modal, that will pop up:

<img width="368" alt="api-modal" src="https://github.com/user-attachments/assets/b1deda78-7398-484e-9bb0-82ef4cf00377">

**Comment by Jhacy456** [comment]
@muchinon please I'll like to take on this issue

**Comment by Jhacy456** [comment]
#170 @muchinon I just created a pr for this task
