### ISSUE TITLE
Admin- Account Configurations

### ISSUE THREAD

**Issue by muchinon** [mestafrica/FraudWatch#142]
Add UI for Configurations

After Admin Clicks Configurations:

<img width="157" alt="tut" src="https://github.com/user-attachments/assets/3b7a0973-c863-4c65-8e6e-2e170d5b04f6">

Unexpanded: 

<img width="514" alt="config-unexpan" src="https://github.com/user-attachments/assets/0e383603-c7e9-46ef-b130-41f124666b76">

Expanded:

<img width="514" alt="config-expan" src="https://github.com/user-attachments/assets/e016568c-e8a5-4b27-a925-f65a1d1e8d64">

**Comment by Miley-Afful** [comment]
@muchinon @alexboateng please i would like to work on this

**Comment by Miley-Afful** [comment]
@muchinon @alexboateng Waiting for review
