### ISSUE TITLE
Delete Report

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#15]
**Endpoint: /api/fraud/reports/delete/{reportId}**
Method: DELETE
Description: Allows users to delete their fraud report.
Authorization Required: Yes

**Security Measures:**
Authorization Check: Ensure the user is authenticated and owns the report.

**Feedback:**
Success: "Your fraud report has been successfully deleted."
Failure: "You do not have permission to delete this report or it does not exist."

Note: Add test cases for all scenarios
Only Owners of a record should delete the record

**Comment by VidaOwusu** [comment]
@alexboateng I want to take up this issue
