### ISSUE TITLE
Add Spacing between API keys and Reported numbers & Improve Search results UI

### ISSUE THREAD

**Issue by muchinon** [mestafrica/FraudWatch#150]
1. add spacing between API keys and Reported numbers
<img width="761" alt="Screenshot 2024-11-10 200707" src="https://github.com/user-attachments/assets/fa7d8271-afe8-4148-ae96-0a3c78bd4c1c">

reference:
<img width="391" alt="Screenshot 2024-11-10 201002" src="https://github.com/user-attachments/assets/4a4aa726-6a04-4b9b-ae7e-802190bc7222">

2.  Improve search results UI,
change from this:
<img width="1167" alt="Screenshot 2024-11-10 201218" src="https://github.com/user-attachments/assets/148b7cff-7aa1-44ec-a310-df4c687b39e8">

to this:
<img width="654" alt="Screenshot 2024-11-10 201154" src="https://github.com/user-attachments/assets/bc3b1529-d9dd-4ac9-bf78-62a2f9126599">

**Comment by Miley-Afful** [comment]
@muchinon please i would like to work on this

**Comment by Miley-Afful** [comment]
@muchinon please I am done working on this. Waiting for review
