### ISSUE TITLE
Integrate API to Report Fraudulent Number (Fix)

### ISSUE THREAD

**Issue by muchinon** [mestafrica/FraudWatch#151]
Properly integrate the api so this reporting flow works

<img width="782" alt="Screenshot 2024-11-10 202053" src="https://github.com/user-attachments/assets/b4dc37b3-e3de-4155-87c7-d3700f1425ef">

The API's are semi integrated so make them work

**Comment by Miley-Afful** [comment]
@muchinon I will like to work on this, please
