### ISSUE TITLE
View Reported Number upon Clicking

### ISSUE THREAD

**Issue by muchinon** [mestafrica/FraudWatch#153]
Clicking this: 
<img width="729" alt="Screenshot 2024-11-10 202741" src="https://github.com/user-attachments/assets/720919f2-f75a-4e09-8d85-7832380194a2">

Should show this (Create the UI for this if its not available):

<img width="770" alt="Screenshot 2024-11-10 202925" src="https://github.com/user-attachments/assets/95f11506-09dc-4f5c-b619-5db15cff5fe6">

Use the existing Nav Bar

**Comment by Jhacy456** [comment]
@muchinon I want to be assigned this issue

**Comment by Jhacy456** [comment]
#160 @muchinon please i have completed my task and raised a pr
