### ISSUE TITLE
Integrate Create API Keys

### ISSUE THREAD

**Issue by muchinon** [mestafrica/FraudWatch#154]
API :  https://www.loom.com/share/e098fbfd6f0f4097abf1e429658533b5?sid=d18f5e6c-2eb3-48b0-aa66-7e0450f7798b

Implement the entire Create API flow:
<img width="742" alt="Screenshot 2024-11-10 203248" src="https://github.com/user-attachments/assets/67a55f5d-05c9-4aa7-b0f6-52edd3e0933f">
<img width="765" alt="Screenshot 2024-11-10 203330" src="https://github.com/user-attachments/assets/b7e35e7f-e1df-4847-91d9-58c037214224">

<img width="910" alt="Screenshot 2024-11-10 203423" src="https://github.com/user-attachments/assets/f3577da2-36a0-4eb2-8626-dfffd52d2320">
<img width="736" alt="Screenshot 2024-11-10 203310" src="https://github.com/user-attachments/assets/6fb2099d-168b-4226-9be8-55b7afa7d84b">

All components should be available, but create the UI for any component you can't find

**Comment by Jhacy456** [comment]
@muchinon I will like to take on this issue

**Comment by Jhacy456** [comment]
#166 @muchinon I have finished my task and raised a pr
