### ISSUE TITLE
Implement Change Password API

### ISSUE THREAD

**Issue by muchinon** [mestafrica/FraudWatch#155]
**Endpoint**: /api/auth/change-password
- **Method:** POST
- **Description:** Allow authenticated users to change their account password
- **Authorization Required:** Yes

**Validations**
New password:
Minimum 8 characters
Must include at least one number
Cannot be same as current password

**Feedback**
Success: "Password changed successfully" ; HTTP Status: 200

Failure: "New password does not meet requirements"; HTTP Status: 400

**Comment by Andrew-Sackey** [comment]
please assign me this issue
