### ISSUE TITLE
Implement Adding Vote API

### ISSUE THREAD

**Issue by muchinon** [mestafrica/FraudWatch#156]
<img width="388" alt="Screenshot 2024-11-10 205630" src="https://github.com/user-attachments/assets/122b244c-0f49-440f-9956-683262b959ef">

**Endpoint**: `/api/votes`

**Method**: POST

**Description**: Allow users to vote on specific fraud report.

**Authorization Required**: Yes

**Feedback**
Success:
Vote recorded successfully
Updated vote count returned
HTTP Status: 200 OK

Failure:
"Content not found"
"Unauthorized to vote"
"Invalid vote type"
HTTP Status: 400 Bad Request

**Comment by Barmoo** [comment]
kindly assign #156 to me (BARMOO
