### ISSUE TITLE
Check Number Status

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#16]
**Endpoint: /api/fraud/check/{phone}**
Method: GET
Description: Allows users to query the database to check if a phone number is reported as fraudulent.
Authorization Required: Yes

**Path Parameter:**
Phone Number: The phone number to check for fraud reports.

**Validations:**
Phone Number: Must be in a valid format and typically normalized to ensure consistency in database queries.
Security Measures:

Authorization Check: Verify that the user is authenticated to access this service. This helps in monitoring and limiting access to sensitive data.

Input Sanitization: Ensure that the input phone number is sanitized to prevent SQL injection and other forms of attacks.

**Feedback:**
Success:
If the number has been reported, return a detailed report including dates, network, status, and any user comments.
If the number has not been reported, a message like "No reports found for this number."

**Failure:**
If the phone number is invalid, return an error message such as "Invalid phone number format."
If unauthorized access is attempted, a message like "You do not have permission to access this information."

Note: Add test cases for all scenarios

**Comment by muchinon** [comment]
@alexboateng  I want to pick up this issue

**Comment by muchinon** [comment]
https://github.com/mestafrica/mobile-wallet-fraud-database/pull/54
