### ISSUE TITLE
Reusable Inputs

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#17]
1. Reusable Password input with a toggle button that toggles visibility
2. A Reusable text Input with custom props eg. placeholder
3. A Reusable phone Input 
4. A Reusable radio button with label
5. A Reusable input with an icon for search

All text inputs should accept all the important props eg. Label, value etc

![Screenshot 2024-07-25 at 1 19 42 PM](https://github.com/user-attachments/assets/5a624508-de4d-476f-992a-009161c1685c)
![Screenshot 2024-07-25 at 1 19 54 PM](https://github.com/user-attachments/assets/9037ae19-f690-474e-9756-26cd8fb68b89)

**Comment by Corletey** [comment]
I would like to pick this issue please
