### ISSUE TITLE
Admin- Integrate API for Login

### ISSUE THREAD

**Issue by muchinon** [mestafrica/FraudWatch#172]
Integrate APIs for login on the frontend admin:

Reference Log In API:  https://www.loom.com/share/facbc508db12407a8fea94a8138ba5b3?sid=40da2751-7e26-44d7-9c92-0d2670e0faca

Add frontend validations

**Comment by Jhacy456** [comment]
@muchinon I will like to take in this issue

**Comment by Jhacy456** [comment]
#175 @muchinon I just raised a pr
