### ISSUE TITLE
Reusable buttons

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#18]
A Reusable button component which can be used in multiple scenarios eg. outline, solid etc with custom labels and props
- A button can also have an icon
- Same button component with different props should present a s below
![Screenshot 2024-07-25 at 1 23 11 PM](https://github.com/user-attachments/assets/72789a37-09dc-489b-a929-d25147bcfc65)
![Screenshot 2024-07-25 at 1 23 22 PM](https://github.com/user-attachments/assets/b5a2452d-b1ed-4121-a8e9-f6b6a689f874)
![Screenshot 2024-07-25 at 1 23 42 PM](https://github.com/user-attachments/assets/af9a89b0-f9e0-49d6-842e-d59bc5fd5170)

**Comment by MsBaidoo** [comment]
@alexboatengIi want to take this issue
