### ISSUE TITLE
Setup Frontend

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#2]
1. Create a folder called frontend
2. Create a new Vite project with the ReactJs + TypeScript + TailwindUI

**Comment by MsBaidoo** [comment]
@alexboateng MsBaidoo

**Comment by MsBaidoo** [comment]
@alexboateng please is tailwind CSS same as TailwindUI?

**Comment by alexboateng** [comment]
@MsBaidoo Yes its same

**Comment by alexboateng** [comment]
> @alexboateng please is tailwind CSS same as TailwindUI?

@MsBaidoo Yes its same

**Comment by MsBaidoo** [comment]
@alexboateng thank you
