### ISSUE TITLE
Home Page (Empty State+ Logged Out)

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#20]
Home page where the user is logged out and no data available
- Use Reusable components (Nav bar, Inputs and buttons) already added
![Screenshot 2024-07-25 at 1 44 17 PM](https://github.com/user-attachments/assets/04671058-a0ce-4294-b2f8-32f5b38af58a)
![Screenshot 2024-07-25 at 1 44 26 PM](https://github.com/user-attachments/assets/6ece945b-1ccb-49e6-ba77-144a30968284)

**Comment by E1ta91** [comment]
@alexboateng please i would like to take this issue
