### ISSUE TITLE
Sign Up, Login and Reset Password Modals

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#21]
Create 3 Modal components for Login, signup and Reset password using reusable buttons and inputs components

![Screenshot 2024-07-25 at 1 47 25 PM](https://github.com/user-attachments/assets/4e743141-0f2e-4f68-a873-02c772bc1b2d)

**Comment by MsBaidoo** [comment]
@alexboateng i want to take this issue

**Comment by EMMIE-J** [comment]
@alexboateng I will pick up this issue

**Comment by Corletey** [comment]
I would like to take up this issue from @EMMIE-J

**Comment by alexboateng** [comment]
thanks @Corletey

**Comment by alexboateng** [comment]
<img width="682" alt="Screenshot 2024-08-14 at 12 20 44 PM" src="https://github.com/user-attachments/assets/64031241-4ee3-4f84-b8ba-f42fb70e9d3f">
<img width="740" alt="Screenshot 2024-08-14 at 12 21 04 PM" src="https://github.com/user-attachments/assets/406b2caf-af6e-4284-850e-1faca998763e">
<img width="740" alt="Screenshot 2024-08-14 at 12 21 16 PM" src="https://github.com/user-attachments/assets/831237e2-6390-4e41-93ae-a149962849d1">
<img width="739" alt="Screenshot 2024-08-14 at 12 21 30 PM" src="https://github.com/user-attachments/assets/f1cf9102-bbfa-403d-8589-dccda34614bc">
<img width="748" alt="Screenshot 2024-08-14 at 12 21 41 PM" src="https://github.com/user-attachments/assets/290ffef9-38cc-4aac-9ec8-ad70c5bf9eea">

**Comment by alexboateng** [comment]
@Corletey i have attached all the pages

**Comment by muchinon** [comment]
@Corletey kindly start working on this issue

**Comment by Corletey** [comment]
@muchinon I believe I have already completed this issue
