### ISSUE TITLE
Reported Numbers

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#28]
Add a Table for reported phone numbers
- It should be paginated with filters as in the UI
- Use Empty state from #20 

![Screenshot 2024-07-29 at 1 09 48 PM](https://github.com/user-attachments/assets/23d65ca2-64cb-42ba-addd-97cc0d6eb6e2)

**Comment by E1ta91** [comment]
@alexboateng  please I would like to take up this issue
