### ISSUE TITLE
Add Login | Reset password - Admin

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#31]
Create UI for login and Reset password for Admin
- You can copy any relevant reusable component from the user app 
![Screenshot 2024-07-29 at 1 25 49 PM](https://github.com/user-attachments/assets/3af031b7-d058-4486-abd7-565c9f0dd53f)
![Screenshot 2024-07-29 at 1 25 56 PM](https://github.com/user-attachments/assets/eca96e9c-ee46-4aa9-8a0b-09be5c859fda)
![Screenshot 2024-07-29 at 1 26 04 PM](https://github.com/user-attachments/assets/82137658-6688-4a9e-9af3-5884feb9d65e)

**Comment by Rilian0031** [comment]
@alexboateng i will pick this issue
