### ISSUE TITLE
Nav Bar - Admin

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#32]
Create a reusable nav bar component for the admin

![Screenshot 2024-07-29 at 1 29 00 PM](https://github.com/user-attachments/assets/a34c3c45-fb70-4735-bca4-851b89aab307)
![Screenshot 2024-07-29 at 1 29 44 PM](https://github.com/user-attachments/assets/532703bc-4fd8-46dd-8564-7e81ca8a245a)

**Comment by Corletey** [comment]
I would like to pick this up please
