### ISSUE TITLE
Search Results

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#47]
Add UI Modals for Number search and Delete request

![Screenshot 2024-08-07 at 3 40 25 PM](https://github.com/user-attachments/assets/060bf2f3-3ea0-4735-92e9-e4b7de1c793d)
![Screenshot 2024-08-07 at 3 40 36 PM](https://github.com/user-attachments/assets/28eb9f04-48dc-454d-8bff-b3762765da98)
![Screenshot 2024-08-07 at 3 41 01 PM](https://github.com/user-attachments/assets/f02bb2b8-9fc6-4525-ba59-30ab93d67fb2)

**Comment by E1ta91** [comment]
@alexboateng I would like to pick up this issue
