### ISSUE TITLE
Add UI For Nav Dropdowm

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#48]
Add dropdown options when hamburger icon is clicked
<img width="588" alt="Screenshot 2024-08-06 at 8 47 20 AM" src="https://github.com/user-attachments/assets/f4247f47-1982-4ae2-89bf-9152b38a7fb4">

**Comment by Rilian0031** [comment]
@alexboateng i will pick this issue

**Comment by muchinon** [comment]
@Rilian0031 kindly work on this issue

**Comment by Jhacy456** [comment]
My name is Jacinta Akpene Sadzi and I will like to handle this issue

**Comment by Jhacy456** [comment]
@alexboateng please I will like to take on this issue

**Comment by Jhacy456** [comment]
#119 @alexboateng @muchinon Please I'm done with the task and created a pr
