### ISSUE TITLE
Sign Up

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#5]
**Endpoint: /api/auth/register**
Method: POST
Description: Allows new users to create an account by providing necessary information such as username, email, and password.
Authorization: False

- First name
- Last name
- Email address
- Phone number
- Password

Add validations and Verifications

**1.First Name & Last Name:**
    - Must not be empty.
    - Must enforce character limits (e.g., 255 characters).

**2. Email Address:**
    - Must be in a valid email format.
    - Should be unique within the database to avoid duplicate accounts.
    - normalized by converting to lower case to ensure consistency in storage and checks.

**3. Phone Number:**
    - Must be valid
    - Should be unique within the database to avoid duplicate accounts.

**4. Password**
    - Must meet complexity requirements (e.g., minimum 8 characters, includes numbers)
    - Encrypt password

**Feedback on Validation Errors:** Provide clear and immediate feedback on any validation errors during registration.

Note: Add test cases for all scenarios

**Comment by muchinon** [comment]
@alexboateng I would like to pick up this issue

**Comment by muchinon** [comment]
https://github.com/mestafrica/mobile-wallet-fraud-database/pull/23
