### ISSUE TITLE
Report Fraud Numbers UI

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#50]
Add UI Modal for reporting fraud Numbers
Should be step-wise
Clicking next moves to the next form

![Screenshot 2024-08-07 at 3 43 34 PM](https://github.com/user-attachments/assets/046141dc-dc14-45e7-9b6e-2b9ea72e1e5c)
![Screenshot 2024-08-07 at 3 43 44 PM](https://github.com/user-attachments/assets/1adfb8a4-e8dc-4e20-868c-bb0c7c697c13)
![Screenshot 2024-08-07 at 3 44 40 PM](https://github.com/user-attachments/assets/0d89a295-9122-467d-a177-ff6bfe7d5f9e)
![Screenshot 2024-08-07 at 3 45 33 PM](https://github.com/user-attachments/assets/eba2675c-a425-4b40-8127-bc2373d41b80)

**Comment by Corletey** [comment]
I would like to pick up this issue. 
However, is there a specific package you recommend I use for the form navigation?

**Comment by alexboateng** [comment]
You can use state management @Corletey
