### ISSUE TITLE
Create API Key

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#56]
Endpoint: /api/keys/generate
Method: POST
Description: Allows users to generate a new API key.
Authorization Required: Yes

**Parameters:**
Name: A descriptive name for the API key to help users identify its use.
Domains (optional): A list of domains where the API key can be used, to restrict usage to specific domains if needed.

**Validations:**
Name:
Must not be empty.
Should be a string with a reasonable length limit (e.g., 100 characters).
Domains:
Each domain must be a valid domain format.
Domains are optional, but if provided, they must be checked for uniqueness against existing domain restrictions on the user's other keys to prevent conflicts.

**Security Measures:**
Authorization Check: Verify that the user is authenticated before allowing API key generation.
Rate Limiting: Implement rate limiting to prevent abuse of the API key generation process.

**Feedback:**
Success: "API key generated successfully."
Failure: Detailed error messages based on the validation that failed, such as "Invalid domain format."

**Comment by muchinon** [comment]
@alexboateng I would like to pick up this issue

**Comment by muchinon** [comment]
https://github.com/mestafrica/mobile-wallet-fraud-database/pull/61
