### ISSUE TITLE
Get API Key

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#57]
Endpoint: /api/keys
Method: GET
Description: Enables users to view all their generated API keys.
Authorization Required: Yes

**Security Measures:**
Authorization Check: Ensure the user is authenticated and has permission to view their own API keys.

**Feedback:**
Success: Returns a list of all API keys associated with the user.
Failure: "You do not have any API keys or do not have permission to view them."

**Comment by VidaOwusu** [comment]
@alexboateng I want to pick up this issue
