### ISSUE TITLE
Delete API Key

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#58]
Endpoint: /api/keys/{keyId}
Method: DELETE
Description: Allows users to delete an API key.
Authorization Required: Yes

**Parameters:**
Key ID: The unique identifier for the API key to be deleted.

**Security Measures:**
Authorization Check: Verify that the user is authenticated and owns the API key before deletion.

**Feedback:**
Success: "API key deleted successfully."
Failure: "You do not have permission to delete this API key or it does not exist."**

**Comment by Sarah0360** [comment]
@alexboateng I will like to pick up this issue
