### ISSUE TITLE
Update API Key

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#59]
Endpoint: /api/keys/restrict/{keyId}
Method: PUT
Description: Allows users to add or update domain restrictions for an existing API key.
Authorization Required: Yes

**Parameters:**
Domains: A list of new or updated domains for restriction.
Validations:
Domains:
Each domain must be in a valid format.
Check for domain uniqueness within the user's API keys to ensure no duplicate restrictions.

**Security Measures:**
Authorization Check: Ensure the user is authenticated and owns the API key before updating restrictions.
Input Sanitization: Validate and sanitize the input domains to avoid injection attacks.

**Feedback:**
Success: "Domain restrictions updated successfully."
Failure: "Failed to update domain restrictions. Ensure domains are valid and unique."

**Comment by Sarah0360** [comment]
@alexboateng I will like to pick up this issue

**Comment by muchinon** [comment]
@alexboateng I would like to pick up the issue

**Comment by muchinon** [comment]
https://github.com/mestafrica/mobile-wallet-fraud-database/pull/64
