### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#6]
**Endpoint: /api/auth/login**
Method: POST
Description: Authenticates users by verifying their email and password.
Authorization Required: No
Parameters:
  Email: User's email address.
  Password: User's password.

**Validations:**
**Email Address:**
    Must be in a valid email format.
    Ensure the email is registered in the database before attempting to authenticate.

**Password:**
    Must not be empty.
    Validate the password against the hashed password stored in the database.

**Feedback:**
Provide clear messages for authentication failures, such as "Invalid email or password" without specifying which is incorrect for security purposes.

Note: Add test cases for all scenarios

**Comment by VidaOwusu** [comment]
@alexboateng I want to work on this issue

**Comment by VidaOwusu** [comment]
@alexboateng I want to work on this issue
