### ISSUE TITLE
Integrate APIs for Sign UP and Login

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#68]
Integrate apis for sign up and frontend
Reference signup api: https://www.loom.com/share/d1b2e2d37de747cab41445ed0337db3d?sid=2b2bc0f8-97f8-4752-be6e-7c88c9b59002
Login api: https://www.loom.com/share/4880b1ca532e4ba38783f68966e61922?sid=3be26a6e-47a1-4964-90d6-151b2ce18b65

Add frontend validations as well

**Comment by Corletey** [comment]
I would like to pick up this issue
