### ISSUE TITLE
Add UI For list of users 

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#70]
Add Users list
Use UI from #32 
<img width="1275" alt="Screenshot 2024-08-14 at 9 00 44 AM" src="https://github.com/user-attachments/assets/e559e19f-1d58-45d1-86d5-5d152e7e48d4">

**Comment by E1ta91** [comment]
@alexboateng Please I would like to pickup this issue

**Comment by muchinon** [comment]
@E1ta91 kindly start with this issue

**Comment by alexboateng** [comment]
#89
