### ISSUE TITLE
Admin - User details

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#71]
Add UI for User details
Use nav from #32 
<img width="1194" alt="Screenshot 2024-08-14 at 9 02 42 AM" src="https://github.com/user-attachments/assets/f0003f5f-45b4-4944-be99-2cc2aa4e6bc7">

**Comment by MsBaidoo** [comment]
@alexboateng please i want to take this issue

**Comment by muchinon** [comment]
@MsBaidoo kindly start with this issue
