### ISSUE TITLE
Reset Password (Send Email)

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#8]
**Endpoint: /api/auth/password/recover**
Method: POST
Description: Initiates password recovery process by sending a reset code to the user via email.
Authorization Required: No

**Parameters:**
Email: User's email address.

**Validations:**
**Email Address:**
    Must be in a valid email format.
    Verify that the email exists in the database to ensure the recovery process is initiated for a valid user.

**Security Measures:**
   Email Verification: Send a password code via email to confirm user identity.  (You can use Twilio if you have access to it)

**Feedback:**
   Provide feedback such as "If your email is registered with us, you will receive a password recovery instruction."

Note: Add test cases for all scenarios

**Comment by VidaOwusu** [comment]
@alexboateng I want to take on this issue

**Comment by alexboateng** [comment]
#34
