### ISSUE TITLE
Reset Password (Verify Code)

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#9]
**Endpoint: /api/auth/password/verify-code**
Method: POST
Description: Verifies the code sent to the user during the password recovery process.
Authorization Required: No

**Parameters:**
Email Address: User's email address.
Code: The verification code sent to the user's email.

**Validations:**
**Email Address:**
    Must be in a valid email format.
    Ensure the email is associated with a pending password reset request.
**Code:**
    Must match the code sent to the user's email.
    Check that the code has not expired.

**Security Measures:**
    Code Expiry: Ensure the verification code expires after a set duration (e.g., 30 minutes) to enhance security.

**Feedback:**
    Provide appropriate feedback based on whether the code matches or not, such as "Invalid or expired code."

Note: Add test cases for all scenarios

**Comment by Sarah0360** [comment]
@alexboateng I will take up this issue
