### ISSUE TITLE
Admin - Add Reported number details (Modal)

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#92]
On clicking an item or a reported case and delete record, A modal with the details of the reported case is shown or the delete modal is opened
![Screenshot 2024-10-29 at 9 35 51 AM](https://github.com/user-attachments/assets/bef84983-7ca2-4082-9ba4-4b734d031db9)

**Comment by odeifuo44** [comment]
@muchinon @alexboateng I'm working on this
