### ISSUE TITLE
Admin - Toggle & Modal for already removed number

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#93]
1. Clicking on Toggle (Show removed reports) shows a list of removed numbers only.
2. Clicking on each opens the modal.
3. Attachments should open attached images
![Screenshot 2024-10-29 at 9 47 46 AM](https://github.com/user-attachments/assets/523b7179-c2b1-4b69-bcea-3351fe5d47d5)

**Comment by Miley-Afful** [comment]
@alexboateng please i would like to take a chance on this

**Comment by Miley-Afful** [comment]
waiting for review

**Comment by Miley-Afful** [comment]
#107 
@alexboateng please i have created a pull request for this. waiting for review

**Comment by alexboateng** [comment]
LGTM
