### ISSUE TITLE
Admin - User Details

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#94]
- Clicking on a user should open a user details page with the details
![Screenshot 2024-10-29 at 9 51 35 AM](https://github.com/user-attachments/assets/ac2aae4f-3e7d-412c-ab0f-2a056818b079)
![Screenshot 2024-10-29 at 9 52 41 AM](https://github.com/user-attachments/assets/49d8cdbe-e7ab-4724-b1f7-55e253ddfad3)

**Comment by Jhacy456** [comment]
@alexboateng please I will like to take on this issue

**Comment by Jhacy456** [comment]
#104 
Please I'm done creating the pull request @alexboateng

**Comment by alexboateng** [comment]
Changes requested on PR @Jhacy456

**Comment by alexboateng** [comment]
LGTM
