### ISSUE TITLE
Admin - Add requests table

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#95]
- Add requests table to existing request tab
![Screenshot 2024-10-29 at 9 54 13 AM](https://github.com/user-attachments/assets/830738c5-e7a0-4634-9a82-caf8463551ac)

Empty State
![Screenshot 2024-10-29 at 9 54 29 AM](https://github.com/user-attachments/assets/66a3451e-90b5-4be4-b50a-bc230babacd8)

**Comment by Miley-Afful** [comment]
@alexboateng please i would like to continue with this

**Comment by Miley-Afful** [comment]
@alexboateng and @muchinon Please i am done with this task, waiting for review
