### ISSUE TITLE
Admin - Hamburger popover | My Account

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#96]
Clicking on the hamburger icon should should open a popover
![Screenshot 2024-10-29 at 9 57 30 AM](https://github.com/user-attachments/assets/81a1c51b-08d5-4975-876c-5ef257ead368)

Add my account page
![Screenshot 2024-10-29 at 9 56 30 AM](https://github.com/user-attachments/assets/72c0e8c5-a1be-42fa-a34e-ab60a64a81b8)

**Comment by Miley-Afful** [comment]
@alexboateng please i would like to work on this

**Comment by Miley-Afful** [comment]
@muchinon and @alexboateng Please I'm done working on this, waiting for review
