### ISSUE TITLE
Admin - Manage Admins

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#97]
- Show lists of admins
- Add new admin modal

![Screenshot 2024-10-29 at 9 58 20 AM](https://github.com/user-attachments/assets/66850c6e-4062-4626-ad6e-c190a8bb303e)
![Screenshot 2024-10-29 at 9 58 25 AM](https://github.com/user-attachments/assets/cb6cd233-0a7a-4865-9ead-21f16fab1f4a)

**Comment by Jhacy456** [comment]
@muchinon I will like to take this issue

**Comment by Jhacy456** [comment]
#134 @muchinon please I finished with my task and created a pr
