### ISSUE TITLE
Admin - Login

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#98]
**Endpoint: /api/admin/login**
Method: POST
Description: Authenticates admin users by verifying their email and password.
Authorization Required: No
Parameters:
Email: Admin's email address.
Password: Admin's password.

**Validations:**
**Email Address:**
Must be in a valid email format.
Ensure the email is registered in the admin database before attempting to authenticate.
**Password:**
Must not be empty.
Validate the password against the hashed password stored in the database.

**Feedback:**
Success: "Login successful."
Failure: "Invalid email or password."

**Comment by Barmoo** [comment]
good morning Alex
i would like to be assigned  the Login

**Comment by Barmoo** [comment]
@alexboateng please how do i get the registration of the admin?

**Comment by Barmoo** [comment]
Because cannot login successfully without the register

**Comment by alexboateng** [comment]
Merged
