### ISSUE TITLE
Admin - Logout

### ISSUE THREAD

**Issue by alexboateng** [mestafrica/FraudWatch#99]
**Endpoint: /api/admin/logout**
Method: POST
Description: Logs out admin users by invalidating their authentication token.
Authorization Required: Yes

**Feedback:**
Success: "You have been logged out successfully."
Failure: "Logout failed. Please try again."

**Comment by ejebulley** [comment]
I will work on the logout

**Comment by ejebulley** [comment]
#99 https://www.loom.com/share/3cf0318a1ac2486fb78946271f45f4a4?sid=c98f7580-c8bd-4c7a-8f7e-e9d1fa4c2024

**Comment by alexboateng** [comment]
@ejebulley Where is a PR link and add the review label if ready to be reviewed
